SELECT 
    CAST(response_id AS UNSIGNED) AS response_id,
    CAST(can_afford_healthcare AS CHAR(10)) AS can_afford_healthcare,
    CAST(need_medical_treatment AS CHAR(50)) AS need_medical_treatment,
    CAST(satisfaction_with_health AS CHAR(50)) AS satisfaction_with_health,
    CAST(enough_to_eat AS CHAR(10)) AS enough_to_eat,
    CAST(food_supports_health_needs AS CHAR(10)) AS food_supports_health_needs,
    CAST(frequency_of_eating_fresh_fruit_vegetables AS CHAR(50)) AS frequency_of_eating_fresh_fruit_vegetables,
    CAST(healthy_food_expensive AS CHAR(10)) AS healthy_food_expensive,
    CAST(reason_not_eating_healthy_transportation AS CHAR(255)) AS reason_not_eating_healthy_transportation,
    CAST(reason_not_eating_healthy_time AS CHAR(255)) AS reason_not_eating_healthy_time,
    CAST(reason_not_eating_healthy_cooking_knowledge AS CHAR(255)) AS reason_not_eating_healthy_cooking_knowledge,
    CAST(reason_not_eating_healthy_supplies_equipment AS CHAR(255)) AS reason_not_eating_healthy_supplies_equipment,
    CAST(reason_not_eating_healthy_household AS CHAR(255)) AS reason_not_eating_healthy_household,
    CAST(reason_not_eating_healthy_not_ready AS CHAR(255)) AS reason_not_eating_healthy_not_ready,
    CAST(reason_not_eating_healthy_other AS CHAR(255)) AS reason_not_eating_healthy_other,
    CAST(violence_communication AS CHAR(255)) AS violence_communication,
    CAST(health_disorder_typhoid AS CHAR(10)) AS health_disorder_typhoid,
    CAST(health_disorder_malaria AS CHAR(10)) AS health_disorder_malaria,
    CAST(health_disorder_hiv_aids AS CHAR(10)) AS health_disorder_hiv_aids,
    CAST(health_disorder_cancer AS CHAR(10)) AS health_disorder_cancer,
    CAST(health_disorder_diabetes AS CHAR(10)) AS health_disorder_diabetes,
    CAST(health_disorder_high_blood_pressure AS CHAR(10)) AS health_disorder_high_blood_pressure,
    CAST(health_disorder_liver_disease AS CHAR(10)) AS health_disorder_liver_disease,
    CAST(health_disorder_ulcers AS CHAR(10)) AS health_disorder_ulcers,
    CAST(health_disorder_other AS CHAR(255)) AS health_disorder_other,
    CAST(protect_from_malaria AS CHAR(255)) AS protect_from_malaria,
    CAST(independently_decide_health_needs AS CHAR(50)) AS independently_decide_health_needs
FROM 
    {{ ref('nigeria_data_v2') }}
